---
- hosts: nodo1
  user: vagrant
  
  tasks:
    - name: vars
      include_vars:
        file: vars
    
    - name: Actualizar
      apt: update_cache=yes

    - name: MariaDB install
      action: apt pkg=mysql-server state=installed

    - name: Python-MariaDB module install
      action: apt pkg=python-mysqldb state=installed

    - name: Configure MariaDB
      mysql_db: name={{ db_name }} state=present
      
    - name: create mariadb user
      become: true
      become_user: root
      mysql_user: name="{{ user }}" host=% password="{{ password }}" priv="*.*:ALL,GRANT"

#    - mysql_user: name={{ user }} password={{ password }} priv='*.*:ALL' state=present
      
    - name: Configuration file MariaDB
      copy: src=mariadb/my.cnf dest=/etc/mysql/mariadb.conf.d/50-server.cnf

    - name: Restart MariaDB
      service: name=mariadb state=restarted

    - name: Bind9 Install
      apt: name=bind9

    - name: Bind9 Zone File
      template: src=bind9/db.directa dest=/var/cache/bind/

    - name: Bind9 Configration File
      template: src=bind9/named.conf.local dest=/etc/bind/

    - name: Resolv.conf File
      template: src=resolv.conf dest=/etc/resolv.conf
 
- hosts: nodo2
  tasks:
  - name: vars
    include_vars:
      file: vars

  - name: MySQL-Client install
    action: apt pkg=mysql-client state=installed

  - name: Nginx install
    action: apt pkg=nginx state=installed
  
  - name: Zip install
    action: apt pkg=zip state=installed

  - name: PHP-MySQL install
    action: apt pkg=php-mysql state=installed

  - name: Configure Nginx
    template: src=nginx/default dest=/etc/nginx/sites-available/default

  - name: Restart Nginx
    service: name=nginx state=restarted

  - name: Install PHP-FPM
    action: apt pkg=php7.0-fpm state=installed

  - name: Resolv.conf File
    template: src=resolv.conf dest=/etc/resolv.conf

  - name: Restart php-fpm
    service: name=php7.0-fpm state=restarted

  - name: Wordpress
    unarchive: src=wordpress/wordpress.zip dest=/var/www/html

  - name: config wordpress
    template: src=wordpress/wp-config-sample.php dest=/var/www/html/wordpress/wp-config.php

  - name: wp-cli install
    copy: src=wordpress/wp-cli.phar dest=/home/vagrant
  
  - name: wp-cli configure
    shell: chmod +x /home/vagrant/wp-cli.phar && mv /home/vagrant/wp-cli.phar /usr/local/bin/wp

  - name: Configure Wordpress
    shell: cd /var/www/html/wordpress && wp core install --url=http://{{ nameweb }} --title="{{ titulo }}" --admin_user="{{ wp_user }}" --admin_password="{{ wp_password }}" --admin_email={{ email }} --allow-root 

